server:
  port: 8888
  servlet:
    context-path: /llm
  compression:
    enabled: false

spring:
  profiles:
    active: druid
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.137.8.130:3306/llm?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 080923

mybatis-plus:
  global-config:
    db-config:
      update-strategy: not_empty
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.coderczh.backend.entity
  mapper-locations: classpath*:mapper/*Mapper.xml

logging:
  config: classpath:logback.xml


deepseek:
  # 硅基流动的url
  base-url: https://api.siliconflow.cn/v1
  # 秘钥(自己注册硅基的账号，并申请即可)
  api-key: sk-izxrtjnozdcvzttaqnrxdpphariewkiskaldqpitbcoafucr