server:
  port: 8888
  servlet:
    context-path: /llm

spring:
  profiles:
    active: druid
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.137.8.130:3306/llm?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 080923
  data:
    redis:
      host: 43.137.8.130
      port: 6379
      password: 080923
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-idle: 16
          min-idle: 8
          max-active: 32
          max-wait: 8ms
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

mybatis-plus:
  global-config:
    db-config:
      update-strategy: not_empty
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.coderczh.backend.entity
  mapper-locations: classpath*:mapper/*Mapper.xml

logging:
  config: classpath:logback.xml